---
- name: Deploy OpenShift CI/CD Project and begin workflow
  hosts: masters
  become: yes
  tasks:
  - name: Create Tasks project
    command: oc new-project dev --display-name="Tasks - Dev"
  - name: Create Stage project
    command: oc new-project stage --display-name="Tasks - Stage"
  - name: Create CI/CD project
    command: oc new-project cicd --display-name="CI/CD"
  - name: Set serviceaccount status for CI/CD project for dev and stage projects
    command: oc policy add-role-to-group edit system:serviceaccounts:cicd -n {{ item }}
    with_items:
    - dev
    - stage
  - name: Start application deployment to trigger CI/CD workflow
    command: oc new-app -n cicd -f cicd_template.yaml
    
