---
- name: Jenkins Setup
  hosts: localhost
  tasks:
    - name: Setup Jenkins with persistent storage
      script: ./scripts/jenkins_persistent.sh

- name: Prepare and Deploy OpenShift Tasks
  hosts: localhost
  tasks:
    - name: Import OpenShift Tasks template to openshift project
      shell: oc project openshift; oc apply -f https://raw.githubusercontent.com/OpenShiftDemos/openshift-tasks/master/app-template.yaml
    - name: Create create necessary image streams
      shell: oc project openshift; oc apply -f https://raw.githubusercontent.com/jboss-openshift/application-templates/master/eap/eap64-image-stream.json
    - name: Create dev environment and install tasks
      shell: oc project cicd-dev; oc new-app openshift-tasks
    - name: Setup build configuration for tasks
      shell: oc project cicd; oc apply -f jenkins_pipeline.yaml
    - name: Trigger initial build pipeline
      shell: oc start-build tasks-bc --follow
